# Generated by Django 5.0.4 on 2024-05-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('content', models.TextField(default='')),
                ('priority', models.IntegerField(default=1)),
                ('isdone', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'todos',
                'managed': True,
            },
        ),
    ]
